apiVersion: batch/v1
kind: Job
metadata:
  name: newman-e2e-job
spec:
  template:
    metadata:
      name: newman
    spec:
      restartPolicy: Never
      containers:
        - name: newman-e2e
          image: juanito0702/newman-e2e:latest
          volumeMounts:
            - name: reports
              mountPath: /etc/newman/reports
      volumes:
        - name: reports
          emptyDir: {}
