version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    image: juanito0702/service-discovery:latest
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_INSTANCE=service-discovery-container
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      zipkin-container:
        condition: service_started
  cloud-config-container:
    image: juanito0702/cloud-config:latest
    build:
      context: ./cloud-config
      dockerfile: Dockerfile
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE=cloud-config-container
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9296/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  api-gateway-container:
    image: juanito0702/api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=api-gateway-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  proxy-client-container:
    image: juanito0702/proxy-client:latest
    build:
      context: ./proxy-client
      dockerfile: Dockerfile
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=proxy-client-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  order-service-container:
    image: juanito0702/order-service:latest
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=order-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  payment-service-container:
    image: juanito0702/payment-service:latest
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=payment-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  product-service-container:
    image: juanito0702/product-service:latest
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=product-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  shipping-service-container:
    image: juanito0702/shipping-service:latest
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=shipping-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  user-service-container:
    image: juanito0702/user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=user-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  favourite-service-container:
    image: juanito0702/favourite-service:latest
    build:
      context: ./favourite-service
      dockerfile: Dockerfile
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_INSTANCE=favourite-service-container
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  locust-container:
    image: juanito0702/locust
    build:
      context: ./locust
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - HOST=http://api-gateway-container:8080
    volumes:
      - ./locust:/app
    depends_on:
      - api-gateway-container
      - order-service-container
      - payment-service-container
      - product-service-container
      - shipping-service-container
      - user-service-container
      - favourite-service-container
  newman-container:
    image: juanito0702/newman-e2e:latest
    build:
      context: ./newman
      dockerfile: Dockerfile
    ports:
      - 8082:8082



